# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 flxk1
# Dedicated-host invariant: only the egress-proxy account has network egress.
# No destination sets and no protocol restriction: relay hosts and QUIC have
# no side door. Render ${PROXY_USER} before loading.

table inet rvnd_egress_lock {
    chain output {
        type filter hook output priority 0; policy drop;
        oif lo accept
        ct state established,related accept
        meta skuid ${PROXY_USER} accept
    }
}
