# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 flxk1
"""Workspace L0 memory layer.

This package implements the append-only JSONL log keyed by folder and exposes
the workspace memory interface used by the runtime.
"""

# Run namespace back-compat shim before anything else imports module-level constants.
# This copies any legacy ``WORKSPACEVERSUM_*`` env vars to ``WORKSPACE_*`` so
# downstream modules see the modern names on first lookup. Idempotent.
from . import _namespace  # noqa: F401

from .mutation_log import (
    LogEvent,
    MutationLog,
    LOG_ROOT_DEFAULT,
    RVND_LOG_ROOT_ENV,
    resolve_log_root,
    folder_hash,
    # Aliased on import, not bound as bare ``seal``: ``rvnd.seal`` is already a
    # submodule (at-rest encryption — ``seal_folder``/``unseal_folder``/
    # ``is_sealed``) that ``memory``, ``draft_store`` and ``backup`` address via
    # ``from . import seal``. Binding the audit-chain seal to that bare name at
    # the package level would shadow the submodule in ``rvnd``'s own namespace.
    seal as seal_audit,
)
from .memory import (
    WorkspaceMemory,
    WebResult,
    discover_folders,
    discover_descendants,
    discover_ancestors,
)
from .folder_context import (
    NoFolderContextError,
    UNSCOPED_SENTINEL,
    current_folder,
    folder_context,
    reset_folder,
    resolve_folder_context,
    set_folder,
    with_folder_context,
)
from .inbox_watcher import (
    DefaultExtractor,
    ExtractedFile,
    Extractor,
    INBOX_SUBDIR,
    InboxWatcher,
    ingest_file,
)
from .nd_routing import (
    BaseNDDispatcher,
    Classification,
    Classifier,
    DefaultClassifier,
    # shadowed at the package root by the later import; aliased so both are reachable
    DispatchResult as RoutingDispatchResult,
    NDDispatcher,
    NDRouter,
    RoutingExtractor,
)
from rvnd.adapters.solver.dimensions import (
    COMPOSITION_TABLE,
    DEFAULT_DIMENSION,
    Dimension,
    classify_predicate,
    classify_query_dimension,
    compose,
    compose_weights,
)
from .policy import (
    Acknowledgement,
    CURRENT_DISCLAIMER_VERSION,
    FolderPolicy,
    InvalidPolicy,
    LocalLlmPolicy,
    LOCAL_LLM_MODE_CLOUD_ALLOWED,
    LOCAL_LLM_MODE_CLOUD_FALLBACK,
    LOCAL_LLM_MODE_LOCAL_ONLY,
    LOCAL_LLM_ON_INSUFFICIENT_ESCALATE_CLOUD,
    LOCAL_LLM_ON_INSUFFICIENT_ESCALATE_HUMAN,
    LOCAL_LLM_ON_INSUFFICIENT_REFUSE,
    OVERSIGHT_DISCLAIMER,
    POLICY_FILENAME,
    LEGACY_POLICY_FILENAME,
    LOCK_DISCLAIMER,
    VALID_LOCAL_LLM_MODES,
    VALID_LOCAL_LLM_ON_INSUFFICIENT,
    disable_discipline,
    disable_oversight,
    disable_lock,
    enable_discipline,
    enable_oversight,
    enable_lock,
    load_policy,
    policy_path,
    save_policy,
)
from .published_policy_pack import (
    ImportedPolicyPack,
    PolicyPackDenied,
    REQUIRED_REVIEWS,
    import_published_policy_pack,
    import_published_policy_pack_into_versum,
)
from .llm_capture import (
    CaptureResult,
    IngestMode,
    LLMExchange,
    OversightLevel,
    VerbosityLevel,
    capture_llm_exchange,
    decide_verbosity,
)
from .web_capture import (
    WebSearchExchange,
    WebSearchResult,
    capture_web_search,
)
from .rule_extractor import (
    RuleFacet,
    extract_rules,
)
from .oversight_extractor import (
    OversightFacet,
    extract_oversight,
)
from .oversight_emit import (
    GroundsBundle,
    DoubtDossier,
    build_grounds_bundle,
    build_dossier,
    needs_dossier,
)
from .breaker import (
    Breaker,
    BreakerState,
    BreakerStatus,
    # shadowed at the package root by the later import; aliased so both are reachable
    Lease as BreakerLease,
    Tripwire,
    cap_grade,
    default_tripwires,
)
from .attestation.core import (
    AttestationResult,
    GreenChecks,
    Probe,
    attest,
    breaker_metrics,
    green_checks,
    signature,
)
from .lens import (
    Admission,
    AdmissionVerdict,
    LearningObject,
    LearningScope,
    Precedent,
    UpdateBudget,
    classify_admission,
    select_precedent,
)
from .oversight import (
    OversightOutcome,
    assess,
)
from .oversight_compose import (
    ComposedOversight,
    ControlChange,
    compose_facets,
    binds_grade,
    check_separation,
    approves_clean,
)
from .oversight_log import (
    TaintFinding,
    record_admission,
    taint_walk,
    mark_tainted,
)
from .oversight_drift import (
    DriftSignal,
    drift_tripwire,
    raise_floor,
)
from .oversight_drift import evaluate as evaluate_drift
from .oversight_dispatch import (
    DispatchResult,
    dispatch,
    record_decision_return,
)
from .domain_nds import (
    AIActRuleND,
    ContractRuleND,
    GDPRRuleND,
    MusicRightsRuleND,
    OversightND,
    register_default_domain_nds,
)
from .crossref_extractor import (
    CrossReference,
    CrossReferenceExtractor,
    extract_cross_references,
    infer_host_instrument,
    register_crossref_nd,
)
from .decisions.extractor import (
    DecisionExtractor,
    DecisionPoint,
    Option,
    extract_decisions,
    register_decision_nd,
)
from .instrument_obligation_extractor import (
    RequiredArtifact,
    RequiredArtifactExtractor,
    extract_required_artifacts,
    register_required_artifact_nd,
)
from .xml_legal import (
    CrossRef,
    DocumentTree,
    ProvisionNode,
    all_cross_refs,
    document_tree_to_text,
    parse_akoma_ntoso,
    parse_formex,
    parse_legal_xml,
)
from .llm_extract import (
    DomainProfile,
    ExtractionResult,
    extract as llm_extract,
    extract_obligations_hybrid,
)
from .workflows import (
    Workflow,
    WorkflowStep,
    active_workflows,
    define_workflow,
    delete_workflow,
    list_workflows,
    list_workflows_for_folder,
    load_workflow,
    recent_dispatches,
    run_workflow,
)
from .registry import (
    DEFAULT_WORKSPACE_DIR,
    add_known_workspace,
    bootstrap_default_workspace,
    list_known_workspaces,
    load_registry,
    remove_known_workspace,
)
from .queue import (
    Lease,
    LeaseStolen,
    QueueEntry,
    cancel_run,
    enqueue_run,
    get_run,
    inspect_stuck_runs,
    list_queue,
    mark_done,
    mark_failed,
    mark_run_done,
    mark_run_failed,
    renew_lease,
    resume_run,
    take_next_run,
)
from .worker import (
    WorkerConfig,
    run_forever as worker_run_forever,
    run_once as worker_run_once,
    stop_worker,
    worker_status,
)
from .pinned_skills import (
    PinnedSkill,
    PinnedSkillStore,
    list_pinned,
    load_companion_catalogue,
    load_pinned_skills,
    pin_skill,
    record_dispatch,
    resolve_skills_for_query,
    save_pinned_skills,
    suggest_companions,
    unpin_skill,
)

__all__ = [
    "__version__",
    "LogEvent",
    "MutationLog",
    "LOG_ROOT_DEFAULT",
    "RVND_LOG_ROOT_ENV",
    "resolve_log_root",
    "folder_hash",
    "seal_audit",
    "WorkspaceMemory",
    "WebResult",
    "discover_folders",
    "discover_descendants",
    "discover_ancestors",
    "current_folder",
    "set_folder",
    "reset_folder",
    "folder_context",
    "with_folder_context",
    "resolve_folder_context",
    "NoFolderContextError",
    "UNSCOPED_SENTINEL",
    "InboxWatcher",
    "DefaultExtractor",
    "ExtractedFile",
    "Extractor",
    "ingest_file",
    "INBOX_SUBDIR",
    "Classification",
    "Classifier",
    "DefaultClassifier",
    "NDDispatcher",
    "BaseNDDispatcher",
    "NDRouter",
    "DispatchResult",
    "RoutingExtractor",
    "Dimension",
    "DEFAULT_DIMENSION",
    "COMPOSITION_TABLE",
    "compose",
    "compose_weights",
    "classify_predicate",
    "classify_query_dimension",
    "FolderPolicy",
    "Acknowledgement",
    "InvalidPolicy",
    "LocalLlmPolicy",
    "LOCAL_LLM_MODE_CLOUD_ALLOWED",
    "LOCAL_LLM_MODE_CLOUD_FALLBACK",
    "LOCAL_LLM_MODE_LOCAL_ONLY",
    "LOCAL_LLM_ON_INSUFFICIENT_ESCALATE_CLOUD",
    "LOCAL_LLM_ON_INSUFFICIENT_ESCALATE_HUMAN",
    "LOCAL_LLM_ON_INSUFFICIENT_REFUSE",
    "VALID_LOCAL_LLM_MODES",
    "VALID_LOCAL_LLM_ON_INSUFFICIENT",
    "POLICY_FILENAME",
    "LEGACY_POLICY_FILENAME",
    "LOCK_DISCLAIMER",
    "OVERSIGHT_DISCLAIMER",
    "CURRENT_DISCLAIMER_VERSION",
    "load_policy",
    "save_policy",
    "policy_path",
    "disable_lock",
    "enable_lock",
    "disable_oversight",
    "enable_oversight",
    "enable_discipline",
    "disable_discipline",
    "ImportedPolicyPack",
    "PolicyPackDenied",
    "REQUIRED_REVIEWS",
    "import_published_policy_pack",
    "import_published_policy_pack_into_versum",
    "LLMExchange",
    "IngestMode",
    "OversightLevel",
    "VerbosityLevel",
    "CaptureResult",
    "capture_llm_exchange",
    "decide_verbosity",
    "WebSearchExchange",
    "WebSearchResult",
    "capture_web_search",
    "RuleFacet",
    "extract_rules",
    "OversightFacet",
    "extract_oversight",
    "GroundsBundle",
    "DoubtDossier",
    "build_grounds_bundle",
    "build_dossier",
    "needs_dossier",
    "Breaker",
    "BreakerState",
    "BreakerStatus",
    "Lease",
    "Tripwire",
    "cap_grade",
    "default_tripwires",
    "AttestationResult",
    "GreenChecks",
    "Probe",
    "attest",
    "breaker_metrics",
    "green_checks",
    "signature",
    "Admission",
    "AdmissionVerdict",
    "LearningObject",
    "LearningScope",
    "Precedent",
    "UpdateBudget",
    "classify_admission",
    "select_precedent",
    "OversightOutcome",
    "assess",
    "ComposedOversight",
    "ControlChange",
    "compose_facets",
    "binds_grade",
    "check_separation",
    "approves_clean",
    "TaintFinding",
    "record_admission",
    "taint_walk",
    "mark_tainted",
    "DriftSignal",
    "drift_tripwire",
    "raise_floor",
    "evaluate_drift",
    "dispatch",
    "record_decision_return",
    "GDPRRuleND",
    "AIActRuleND",
    "MusicRightsRuleND",
    "ContractRuleND",
    "OversightND",
    "register_default_domain_nds",
    "CrossReference",
    "CrossReferenceExtractor",
    "extract_cross_references",
    "infer_host_instrument",
    "register_crossref_nd",
    "DecisionPoint",
    "Option",
    "DecisionExtractor",
    "extract_decisions",
    "register_decision_nd",
    "RequiredArtifact",
    "RequiredArtifactExtractor",
    "extract_required_artifacts",
    "register_required_artifact_nd",
    "DocumentTree",
    "ProvisionNode",
    "CrossRef",
    "parse_akoma_ntoso",
    "parse_formex",
    "parse_legal_xml",
    "document_tree_to_text",
    "all_cross_refs",
    "DomainProfile",
    "ExtractionResult",
    "llm_extract",
    "extract_obligations_hybrid",
    "PinnedSkill",
    "PinnedSkillStore",
    "load_pinned_skills",
    "save_pinned_skills",
    "pin_skill",
    "unpin_skill",
    "list_pinned",
    "resolve_skills_for_query",
    "record_dispatch",
    "load_companion_catalogue",
    "suggest_companions",
    "Workflow",
    "WorkflowStep",
    "define_workflow",
    "delete_workflow",
    "load_workflow",
    "list_workflows",
    "list_workflows_for_folder",
    "run_workflow",
    "recent_dispatches",
    "active_workflows",
    "QueueEntry",
    "enqueue_run",
    "list_queue",
    "take_next_run",
    "renew_lease",
    "mark_done",
    "mark_failed",
    "mark_run_done",
    "mark_run_failed",
    "LeaseStolen",
    "cancel_run",
    "get_run",
    "inspect_stuck_runs",
    "resume_run",
    "WorkerConfig",
    "worker_run_forever",
    "worker_run_once",
    "stop_worker",
    "worker_status",
    "DEFAULT_WORKSPACE_DIR",
    "add_known_workspace",
    "bootstrap_default_workspace",
    "list_known_workspaces",
    "load_registry",
    "remove_known_workspace",
    "RoutingDispatchResult",
    "BreakerLease",
]

from ._version import __version__  # noqa: E402
