# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 flxk1
"""Ed25519 signing for the mutation-log audit chain (0.6.6+).

Layer above the SHA-256 hash chain in mutation_log.py. The hash chain catches
casual tampering (someone deletes or modifies events without recomputing).
Ed25519 closes the *chain rewrite* gap — an adversary with full filesystem
write access could otherwise delete an event, recompute all downstream
prev_hash values, and the chain would re-validate. With Ed25519, every event
is also signed; an adversary who doesn't have the private key cannot forge
valid signatures, so rewrites are detectable.

Key layout (0.6.8 B4 — per-host namespacing):

    ~/.workspace/keys/<host_id>/identity.priv    # operator key (per host)
    ~/.workspace/keys/<host_id>/identity.pub
    ~/.workspace/keys/controller.priv            # controller key (per workspace, NOT per host)
    ~/.workspace/keys/controller.pub

``host_id`` is the first 12 hex chars of ``sha256(hostname + "|" + machine_id)``.
Stable across reboots, distinct across hosts that share a homedir (NFS, MSP).

The controller key is a SEPARATE key used as a co-signer for high-stakes
operations (purge tombstones, erasure). It is workspace-scoped, not
host-scoped — the legal controller is the same entity regardless of which
host performed the action. Generated by the explicit ``workspaces keys
init-controller`` ceremony, never auto-created on first use.

Override the key root via the ``WORKSPACE_KEY_DIR`` env var.

Backward compat: events written before 0.6.6 lack a signature. Verification
accepts them but counts them as ``unsigned_events`` in the chain result.
Existing single-key installs (keys at the flat root, pre-0.6.8) are migrated
to the host-scoped layout on first call via
``migrate_legacy_keypair_to_host_subdir()`` — see B4 in the release plan.
"""

from __future__ import annotations

import hashlib
import logging
import os
import socket
import stat
import subprocess
from pathlib import Path
from typing import Optional

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization
from cryptography.exceptions import InvalidSignature


_log = logging.getLogger(__name__)

DEFAULT_KEY_DIR = Path.home() / ".workspace" / "keys"
"""Default location of the key tree root. Override via WORKSPACE_KEY_DIR env.

After 0.6.8 B4 this is the *root*; identity keys live in
``<root>/<host_id>/identity.{priv,pub}`` and the controller keypair lives
flat at ``<root>/controller.{priv,pub}``.
"""


def _key_root_dir() -> Path:
    """Resolve the active key root (env override > default).

    The root is the top-level directory; per-host subdirectories sit under
    this and the controller keypair sits flat at the root.
    """
    override = os.environ.get("WORKSPACE_KEY_DIR")
    return Path(override).expanduser() if override else DEFAULT_KEY_DIR


KEY_PASSPHRASE_ENV = "WORKSPACE_KEY_PASSPHRASE"
"""Passphrase for private keys at rest. When set, new private keys are
written passphrase-encrypted (PKCS8 BestAvailableEncryption) and encrypted
keys load with it; when unset, keys are written cleartext and filesystem
permissions (0600) are the only protection. Verification paths read the
``.pub`` files and never need the passphrase."""


def _key_encryption() -> serialization.KeySerializationEncryption:
    pw = os.environ.get(KEY_PASSPHRASE_ENV)
    return (serialization.BestAvailableEncryption(pw.encode())
            if pw else serialization.NoEncryption())


def _load_private_key(pem: bytes, path: Path) -> object:
    """Load a PEM private key written in either at-rest mode.

    Cleartext loads directly; an encrypted key loads with the passphrase
    from ``WORKSPACE_KEY_PASSPHRASE``. Raises ``RuntimeError`` naming the
    env var when the key is encrypted and no (or the wrong) passphrase is
    available — a signing path must fail loud, not fall through to a fresh
    identity."""
    try:
        return serialization.load_pem_private_key(pem, password=None)
    except TypeError:
        pw = os.environ.get(KEY_PASSPHRASE_ENV)
        if not pw:
            raise RuntimeError(
                f"private key at {path} is passphrase-protected; set "
                f"{KEY_PASSPHRASE_ENV} to load it"
            ) from None
        try:
            return serialization.load_pem_private_key(pem, password=pw.encode())
        except ValueError as e:
            raise RuntimeError(
                f"private key at {path} did not decrypt with the passphrase "
                f"from {KEY_PASSPHRASE_ENV}: {e}"
            ) from None


# ---------------------------------------------------------------------------
# Host identity (0.6.8 B4)
# ---------------------------------------------------------------------------


def _machine_id() -> str:
    """Best-effort stable machine identifier.

    Order of preference:
      1. ``/etc/machine-id`` (systemd-style; Linux default).
      2. ``/var/lib/dbus/machine-id`` (older Linux fallback).
      3. macOS ``IOPlatformUUID`` via ``ioreg``.
      4. The literal ``"no-machine-id"`` — stable but generic; on platforms
         where we can't probe, hosts that share a homedir will collide.
         Acceptable because hostname still differs in most realistic setups.

    Never raises; failure modes degrade to the constant fallback.
    """
    # Linux paths.
    for p in ("/etc/machine-id", "/var/lib/dbus/machine-id"):
        try:
            data = Path(p).read_text(encoding="utf-8").strip()
            if data:
                return data
        except (OSError, UnicodeDecodeError):
            continue
    # macOS: parse `ioreg -rd1 -c IOPlatformExpertDevice`.
    try:
        out = subprocess.check_output(
            ["ioreg", "-rd1", "-c", "IOPlatformExpertDevice"],
            stderr=subprocess.DEVNULL,
            timeout=2,
        ).decode("utf-8", errors="ignore")
        # Find IOPlatformUUID line: `    "IOPlatformUUID" = "ABCD-..."`
        for line in out.splitlines():
            if "IOPlatformUUID" in line and "=" in line:
                # Extract the quoted value.
                _, _, rhs = line.partition("=")
                rhs = rhs.strip()
                if rhs.startswith('"') and rhs.endswith('"'):
                    val = rhs[1:-1].strip()
                    if val:
                        return val
    except (OSError, subprocess.SubprocessError, subprocess.TimeoutExpired) as e:
        # Documented degrade path ("never raises") — but not silent.
        _log.debug("machine-id probe via ioreg failed: %s", e)
    return "no-machine-id"


HOST_ID_ENV = "WORKSPACE_HOST_ID"
"""Explicit host-identity override. When set, it pins ``host_id`` regardless of the
machine hostname — the recovery/portability path for issue #122. An operator who moved
networks (changing ``socket.gethostname()``) can set this to the host_id that signed an
existing chain to make it verify again."""


def _host_id_pin_path() -> Path:
    """Where the resolved host_id is persisted so it never drifts with the hostname."""
    return _key_root_dir() / "host-id"


def _host_id() -> str:
    """Stable 12-char host identity.

    Resolution order — every branch is stable across reboots AND hostname/network
    changes:
      1. ``WORKSPACE_HOST_ID`` env — explicit override (recovery / portability).
      2. The persisted pin at ``<key-root>/host-id`` — written the first time an id is
         derived, and read verbatim thereafter.
      3. Derive ``sha256(hostname + "|" + machine_id)[:12]`` and persist it to (2).

    Before this pin, the function returned (3) directly. That is NOT stable when the OS
    hostname tracks the network (e.g. macOS with ``HostName`` unset): a chain signed
    under one hostname then failed verification after the machine moved networks and a
    different key was loaded — issue #122. Pinning (1)/(2) fixes that; ``machine_id``
    was already stable, so the hostname was the only moving part.
    """
    env = os.environ.get(HOST_ID_ENV)
    if env and env.strip():
        return env.strip()
    pin = _host_id_pin_path()
    try:
        if pin.is_file():
            pinned = pin.read_text(encoding="utf-8").strip()
            if pinned:
                return pinned
    except OSError:
        pass  # unreadable pin (perms/IO) -> fall through and derive fresh below
    h = socket.gethostname() or "unknown-host"
    m = _machine_id() or "no-machine-id"
    hid = hashlib.sha256(f"{h}|{m}".encode("utf-8")).hexdigest()[:12]
    try:
        pin.parent.mkdir(parents=True, exist_ok=True)
        pin.write_text(hid + "\n", encoding="utf-8")
    except OSError:
        pass  # persistence is best-effort; the derived id still holds this run
    return hid


def _key_dir() -> Path:
    """Active per-host key directory (0.6.8+).

    Returns ``<root>/<host_id>``. Pre-0.6.8 code called this directly to get
    the flat root; callers expecting the legacy shape will read keys from a
    location that no longer matches what a fresh install creates. Use the
    migration helper to bring legacy layouts forward.
    """
    return _key_root_dir() / _host_id()


def _private_key_path() -> Path:
    return _key_dir() / "identity.priv"


def _public_key_path() -> Path:
    return _key_dir() / "identity.pub"


# ---------------------------------------------------------------------------
# Controller key (0.6.8 B4 / D2)
# ---------------------------------------------------------------------------


def _controller_key_dir() -> Path:
    """Controller key directory.

    The controller key is workspace-scoped, NOT per-host, so it sits flat at
    the key root — the same controller signs from every host they touch.
    """
    return _key_root_dir()


def _controller_private_key_path() -> Path:
    return _controller_key_dir() / "controller.priv"


def _controller_public_key_path() -> Path:
    return _controller_key_dir() / "controller.pub"


def ensure_keypair() -> tuple[Ed25519PrivateKey, Ed25519PublicKey]:
    """Return (private, public). Generates a new keypair on first call.

    Private key file is written with 0600 permissions. The public key sits
    alongside it for sharing/verification by third parties.

    Idempotent: subsequent calls load the existing keypair.

    0.6.8 migration: if a pre-0.6.8 keypair is sitting at the FLAT root (no
    per-host subdir), it is silently auto-migrated into the per-host subdir
    on first access here. Operators who want the explicit, audit-logged
    migration should call ``migrate_legacy_keypair_to_host_subdir(audit_log=...)``
    directly — that path writes a chain breadcrumb; this auto-path does not.
    """
    kd = _key_dir()
    priv_path = _private_key_path()
    pub_path = _public_key_path()

    # Auto-migrate from the legacy flat-root location if needed (silent;
    # no audit event — see docstring).
    legacy_priv = _key_root_dir() / "identity.priv"
    legacy_pub = _key_root_dir() / "identity.pub"
    if not priv_path.exists() and legacy_priv.exists():
        kd.mkdir(parents=True, exist_ok=True)
        try:
            os.replace(legacy_priv, priv_path)
            if legacy_pub.exists():
                os.replace(legacy_pub, pub_path)
            try:
                os.chmod(priv_path, stat.S_IRUSR | stat.S_IWUSR)
            except OSError as e:
                _log.debug("chmod 0600 on %s failed (best-effort): %s",
                           priv_path, e)
        except OSError as e:
            # Integrity-relevant: a silent failure here falls through to
            # generating a NEW host identity key — a silent identity change
            # on the signing path. Surface it.
            _log.warning(
                "legacy key migration %s -> %s failed (%s); a new host key "
                "will be generated if none exists at the target",
                legacy_priv, priv_path, e,
            )

    if priv_path.exists():
        priv_bytes = priv_path.read_bytes()
        priv = _load_private_key(priv_bytes, priv_path)
        if not isinstance(priv, Ed25519PrivateKey):
            raise TypeError(
                f"key at {priv_path} is not an Ed25519 private key"
            )
        pub = priv.public_key()
        return priv, pub

    # Fresh generation — atomic first-writer-wins. Two processes racing the
    # first signature used to both pass the exists() check above, both
    # generate, and last-write-win the file; each would then RETURN ITS OWN
    # key, so the loser signed events with a key that was never on disk and
    # verify_chain reported signature failures. The candidate key is written
    # to a unique temp name and the canonical path is claimed with a hard
    # link (atomic create-if-absent); the loser discards its candidate and
    # loads the winner's key. Readers can never observe a partial private
    # key: the canonical name only ever points at fully written bytes.
    kd.mkdir(parents=True, exist_ok=True)
    priv = Ed25519PrivateKey.generate()
    pub = priv.public_key()

    priv_pem = priv.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=_key_encryption(),
    )
    pub_pem = pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    tmp = priv_path.with_name(f".{priv_path.name}.tmp.{os.getpid()}")
    tmp.write_bytes(priv_pem)
    try:
        os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)  # 0600 before it's visible
    except OSError as e:
        _log.debug("chmod 0600 on %s failed (best-effort): %s", tmp, e)
    try:
        os.link(tmp, priv_path)
    except FileExistsError:
        # Lost the race: a concurrent first-caller claimed the identity.
        tmp.unlink(missing_ok=True)
        winner = _load_private_key(priv_path.read_bytes(), priv_path)
        if not isinstance(winner, Ed25519PrivateKey):
            raise TypeError(f"key at {priv_path} is not an Ed25519 private key")
        return winner, winner.public_key()
    except OSError as e:
        # Filesystem without hard links: degrade to a plain move. Non-atomic
        # against a concurrent winner, but no worse than the pre-fix path.
        _log.debug("hard-link claim unavailable (%s); using os.replace", e)
        os.replace(tmp, priv_path)
    else:
        tmp.unlink(missing_ok=True)
    pub_path.write_bytes(pub_pem)

    return priv, pub


def sign_bytes(data: bytes, private_key: Optional[Ed25519PrivateKey] = None) -> str:
    """Sign data and return a hex-encoded signature. Uses default keypair if none provided."""
    if private_key is None:
        private_key, _ = ensure_keypair()
    return private_key.sign(data).hex()


def verify_signature(
    data: bytes,
    signature_hex: str,
    public_key: Optional[Ed25519PublicKey] = None,
) -> bool:
    """Verify a hex-encoded signature against data. Uses default keypair's public if none provided."""
    if public_key is None:
        _, public_key = ensure_keypair()
    try:
        public_key.verify(bytes.fromhex(signature_hex), data)
        return True
    except (InvalidSignature, ValueError):
        return False


def public_key_pem() -> str:
    """Return the active public key in PEM format (for sharing / publication)."""
    _, pub = ensure_keypair()
    return pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("utf-8")


def public_key_fingerprint() -> str:
    """First 16 hex chars of sha256 of the active identity public key bytes.

    Surfaced in ``workspaces status`` so an operator can spot-check that two
    hosts are running the keys they think they're running, and that key
    rotation actually changed something.
    """
    _, pub = ensure_keypair()
    return fingerprint_of(pub)[:16]


def fingerprint_of(pub: Ed25519PublicKey) -> str:
    """Full sha256 hex of an Ed25519 public key's raw bytes — the stable
    identifier a chain pins to (see genesis key registration)."""
    raw = pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return hashlib.sha256(raw).hexdigest()


def identity_fingerprint_or_none() -> Optional[str]:
    """Fingerprint of this host's on-disk identity public key, WITHOUT
    generating one. ``None`` if no keypair exists yet. Read-only: safe on
    verification paths."""
    pub = identity_public_key_or_none()
    return fingerprint_of(pub) if pub is not None else None


def identity_public_pem_or_none() -> Optional[str]:
    """PEM of this host's on-disk identity public key, without generating.
    ``None`` if absent. Embedded in a genesis key_registration event so a
    verifier can recover the pinned key from the chain itself."""
    pub = identity_public_key_or_none()
    if pub is None:
        return None
    return pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("utf-8")


def register_identity() -> tuple[str, str]:
    """Ensure the identity keypair exists and return (fingerprint, PEM) for a
    genesis key_registration. Unlike the ``*_or_none`` readers this is a write
    path — pinning a chain generates the key it commits to if none exists yet."""
    _, pub = ensure_keypair()
    pem = pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("utf-8")
    return fingerprint_of(pub), pem


# ---------------------------------------------------------------------------
# Controller key — D2 / B4 (0.6.8)
# ---------------------------------------------------------------------------


def ensure_controller_keypair() -> tuple[Ed25519PrivateKey, Ed25519PublicKey]:
    """Return (private, public) for the controller key.

    Unlike ``ensure_keypair()``, this is the LEGAL controller's co-signing
    key — used to authorise high-stakes operations (purge tombstones, B5
    erasure). One controller key per workspace; the same key signs from
    every host the controller touches.

    Idempotent: subsequent calls load the existing keypair. Generated on
    first call (or via the explicit ``workspaces keys init-controller``
    ceremony — see ``cli.py``).
    """
    kd = _controller_key_dir()
    priv_path = _controller_private_key_path()
    pub_path = _controller_public_key_path()

    if priv_path.exists():
        priv_bytes = priv_path.read_bytes()
        priv = _load_private_key(priv_bytes, priv_path)
        if not isinstance(priv, Ed25519PrivateKey):
            raise TypeError(
                f"key at {priv_path} is not an Ed25519 private key"
            )
        pub = priv.public_key()
        return priv, pub

    kd.mkdir(parents=True, exist_ok=True)
    priv = Ed25519PrivateKey.generate()
    pub = priv.public_key()

    priv_pem = priv.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=_key_encryption(),
    )
    pub_pem = pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    priv_path.write_bytes(priv_pem)
    pub_path.write_bytes(pub_pem)
    try:
        os.chmod(priv_path, stat.S_IRUSR | stat.S_IWUSR)  # 0600
    except OSError as e:
        _log.debug("chmod 0600 on %s failed (best-effort): %s", priv_path, e)
    return priv, pub


def sign_with_controller(data: bytes) -> str:
    """Sign ``data`` with the controller key. Returns hex-encoded signature.

    Generates the controller keypair on first use. For high-stakes flows
    (B1 purge tombstone, B5 erasure) the operator key signature is
    co-required with this one.
    """
    priv, _ = ensure_controller_keypair()
    return priv.sign(data).hex()


def verify_controller_signature(data: bytes, signature_hex: str) -> bool:
    """Verify ``signature_hex`` over ``data`` against the controller pubkey."""
    _, pub = ensure_controller_keypair()
    try:
        pub.verify(bytes.fromhex(signature_hex), data)
        return True
    except (InvalidSignature, ValueError):
        return False


def identity_public_key_or_none() -> Optional[Ed25519PublicKey]:
    """Load this host's identity PUBLIC key from disk WITHOUT creating it.

    Read-only counterpart of :func:`ensure_keypair` for verification paths:
    reads ``identity.pub`` only, so it needs neither write access nor the
    key passphrase. Returns ``None`` when no keypair exists yet."""
    try:
        pub_path = _public_key_path()
        if pub_path.exists():
            pub = serialization.load_pem_public_key(pub_path.read_bytes())
            if isinstance(pub, Ed25519PublicKey):
                return pub
    except Exception:
        return None
    return None


def controller_public_key_or_none() -> Optional[Ed25519PublicKey]:
    """Load the controller PUBLIC key from disk WITHOUT creating it.

    Returns ``None`` when no controller key is registered. Unlike
    :func:`verify_controller_signature` (which calls
    ``ensure_controller_keypair`` and would auto-generate), this is safe to
    call from read-only paths such as ``verify_chain`` — it never writes.
    """
    priv_path = _controller_private_key_path()
    pub_path = _controller_public_key_path()
    # Read the .pub first: it is always cleartext, so verification works
    # without the key passphrase (and without touching the private key).
    try:
        if pub_path.exists():
            pub = serialization.load_pem_public_key(pub_path.read_bytes())
            if isinstance(pub, Ed25519PublicKey):
                return pub
        if priv_path.exists():
            priv = _load_private_key(priv_path.read_bytes(), priv_path)
            if isinstance(priv, Ed25519PrivateKey):
                return priv.public_key()
    except Exception:
        return None
    return None


def verify_controller_signature_strict(data: bytes, signature_hex: str) -> bool:
    """Verify a controller signature against the on-disk controller pubkey.

    Returns ``False`` (never auto-creates) if no controller key is registered
    or the signature does not validate. Used by ``verify_chain`` to enforce
    two-key purge tombstones: a tombstone that *claims* controller
    co-signature must validate against the registered controller pubkey or it
    is treated as a forgery.
    """
    pub = controller_public_key_or_none()
    if pub is None:
        return False
    try:
        pub.verify(bytes.fromhex(signature_hex), data)
        return True
    except (InvalidSignature, ValueError):
        return False


def public_controller_key_fingerprint() -> str | None:
    """16-hex-char fingerprint of the controller public key, or None.

    Returns ``None`` if the controller keypair has not been initialised yet
    (operator has not run ``workspaces keys init-controller``). Surfaces in
    ``workspaces status`` as ``(none)`` when this is None.
    """
    if not _controller_private_key_path().exists():
        return None
    _, pub = ensure_controller_keypair()
    raw = pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return hashlib.sha256(raw).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Legacy-keypair migration (0.6.8 B4)
# ---------------------------------------------------------------------------


def migrate_legacy_keypair_to_host_subdir(
    *,
    audit_log: "object | None" = None,
) -> str:
    """Move a pre-0.6.8 flat-root keypair into the per-host subdirectory.

    Pre-0.6.8 layout (flat):

        <root>/identity.priv
        <root>/identity.pub

    Post-0.6.8 layout (per-host):

        <root>/<host_id>/identity.priv
        <root>/<host_id>/identity.pub

    Behaviour:
      - If the flat-root keypair exists OUTSIDE a host subdir, atomically
        move it into ``<root>/<host_id>/``. Returns the active 12-char
        ``host_id`` either way (the caller usually wants to print it).
      - If no legacy keypair exists (fresh install, or migration already
        ran), returns the active ``host_id`` and writes no audit event.
      - If ``audit_log`` is provided (a ``MutationLog`` instance), the
        migration emits a ``system`` event with ``extra.kind="key_migration"``
        so the chain is honest about the change.

    Idempotent: second call is a no-op (the legacy file is gone after the
    first call moved it).

    Atomic-ish: uses ``os.replace`` so a crash mid-move can't leave the
    keypair in both locations.
    """
    root = _key_root_dir()
    host_id = _host_id()

    legacy_priv = root / "identity.priv"
    legacy_pub = root / "identity.pub"

    if not legacy_priv.exists() and not legacy_pub.exists():
        return host_id  # nothing to migrate; fresh install or already-migrated

    target_dir = root / host_id
    target_dir.mkdir(parents=True, exist_ok=True)
    target_priv = target_dir / "identity.priv"
    target_pub = target_dir / "identity.pub"

    # If the target already exists, refuse to clobber — operator should
    # resolve manually (might be a fresh host-scoped key generated alongside
    # an un-cleaned legacy keypair).
    if target_priv.exists() or target_pub.exists():
        # Treat as already-migrated for the purposes of returning host_id.
        # If the legacy files are stragglers (target also exists), we leave
        # them in place so the operator notices.
        return host_id

    # Atomic-ish move (rename within the same filesystem).
    moved_from_priv: str | None = None
    moved_from_pub: str | None = None
    if legacy_priv.exists():
        os.replace(legacy_priv, target_priv)
        moved_from_priv = str(legacy_priv)
        try:
            os.chmod(target_priv, stat.S_IRUSR | stat.S_IWUSR)  # 0600
        except OSError as e:
            _log.debug("chmod 0600 on %s failed (best-effort): %s",
                       target_priv, e)
    if legacy_pub.exists():
        os.replace(legacy_pub, target_pub)
        moved_from_pub = str(legacy_pub)

    # Emit an audit-chain breadcrumb if a log was provided.
    if audit_log is not None and (moved_from_priv or moved_from_pub):
        try:
            from .mutation_log import LogEvent  # local import — avoid cycle at import time
            event = LogEvent(
                event="system",
                folder_path=str(getattr(audit_log, "folder_path", "")),
                pair_id=f"key-migration:{host_id}",
                channel="system",
                actor="system:key_migration",
                extra={
                    "kind": "key_migration",
                    "from_path": moved_from_priv or moved_from_pub or "",
                    "to_path": str(target_priv),
                    "host_id": host_id,
                },
            )
            audit_log.append(event)
        except Exception:
            # Best-effort — the migration itself succeeded; failing to log it
            # is loud-noticeable in `workspaces status` chain stats but shouldn't
            # roll back the move.
            pass

    return host_id
