#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 flxk1
"""Surface verifier — the runnable check of what the console exposes.

Matches the engine's declared surface (``_DECLARED_TOOLS`` plus every op-based
facade's ``op="help"`` registry) against the composed page — serve.py's
``compose_classic()``, the shell document plus every panel-pack bundle it
inlines — and reports each op as surfaced (quoted-string match), ambiguous
(generic name matched — human-confirm), or unsurfaced. A panel moved behind
the panel-mount contract (the panel-mount contract)
carries its ops in its own bundle under app/src/panels/, not in
app/src/index.html, so the claim of record has to cover what is actually
served, not the shrinking shell source alone. Matching is quoted-string-
anywhere because panels route ops through ``get(op)`` wrappers. Modules roll up as reached
(static-import closure from mcp_server), internal-declared ("internal by
design" in the docstring), cli-contract (named in
``APPROVED_NONVISUAL_CONTRACTS`` with a documented reason — a supported
non-visual surface rather than a console panel), or unreferenced. Exit 0 =
no NEW unsurfaced op and
no NEW unreferenced module vs docs/evidence/surface-baseline.json; the ledger
docs/evidence/surface-ledger.md is a dated snapshot, this script the claim of record.
Flags: --json FILE | --write-baseline | --ledger.
"""
from __future__ import annotations

import ast
import inspect
import json
import re
import sys
import time
from pathlib import Path
from typing import Iterable

HERE = Path(__file__).resolve().parent.parent
APP_DIR = HERE / "app"
PACKAGE_DIR = HERE / "server" / "src" / "workspaces"
BASELINE = HERE / "docs" / "evidence" / "surface-baseline.json"
LEDGER = HERE / "docs" / "evidence" / "surface-ledger.md"

LEDGER_BEGIN = "<!-- generated by verify_surface.py — edits inside this block are overwritten -->"
LEDGER_END = "<!-- end generated block -->"

INTERNAL_MARK = "internal by design"

# Approved non-visual contracts. A module listed here is a supported operation
# whose surface is the packaged CLI (or MCP) rather than a console panel; each
# entry states the documented reason it has no visual surface. Membership is
# hand-authored — transitive import reach never adds an entry — so a module the
# CLI happens to import does not silently become an accepted contract. Being
# reached from mcp_server or declaring "internal by design" both outrank this
# registry; a module that is none of the three is unreferenced and fails the
# gate until it is surfaced, declared internal, or registered here with a reason.
#
# A classification may name only a module the candidate contains: an entry for a
# module absent from a clean checkout would approve a contract that does not ship.
# Register a module here after it is committed under its own reviewed scope, not
# before — an untracked module must read as a gap, and that gap is not closed by
# a baseline update.
APPROVED_NONVISUAL_CONTRACTS: dict[str, str] = {
    "cli": "packaged 'workspaces' command-line entry point; the CLI is the surface, not a console panel",
    "cli.impl": "command handlers behind the 'workspaces' CLI; non-visual by design",
    "cli.__main__": "python -m workspaces.cli package entry; same contract as the cli entry point",
    "licence_usage": "read-only commercial-capacity evidence exposed by the packaged 'workspaces licence usage' CLI; intentionally non-visual",
    "published_policy_pack": "public Python package import boundary exported from 'workspaces'; policy-pack validation is host/adapter-facing, not a console interaction",
    "worker": "'workspaces run-worker' background queue drainer; a long-running process, not a console interaction",
    "workspace_migrate": "'workspaces migrate' and gc maintenance verbs for relocated workspace logs; operator CLI, non-visual by design",
}


# ---------------------------------------------------------------------------
# Op inventory — from the live help registry
# ---------------------------------------------------------------------------

def load_mcp_module():
    sys.path.insert(0, str(PACKAGE_DIR.parent))
    import workspaces.mcp_server as m
    return m


def load_composed_html() -> str:
    """The page /classic actually serves: the shell document plus every
    panel-pack bundle serve.py's compose_classic() inlines before </body>.
    Importing serve does not start a server — it only defines the
    composition function this gate calls directly."""
    sys.path.insert(0, str(APP_DIR))
    import serve
    return serve.compose_classic()


def build_op_inventory(mcp_module) -> list[dict]:
    """One row per operation. Standalone tools (no ``op`` parameter) count as
    a single row matched by their tool name."""
    rows: list[dict] = []
    for tool_name in mcp_module._DECLARED_TOOLS:
        fn = getattr(mcp_module, tool_name, None)
        if fn is None:
            rows.append({"facade": tool_name, "op": None, "match_token": tool_name,
                         "note": "declared but missing attribute"})
            continue
        params = inspect.signature(fn).parameters
        if "op" not in params:
            rows.append({"facade": tool_name, "op": None, "match_token": tool_name})
            continue
        help_payload = fn(op="help")
        for entry in help_payload.get("ops", []):
            op = entry.get("op")
            if not op:
                continue
            row = {"facade": tool_name, "op": op, "match_token": op}
            for key in ("note", "hook", "doc"):
                if entry.get(key):
                    row[key] = entry[key]
            rows.append(row)
    return rows


# ---------------------------------------------------------------------------
# Three-state matcher
# ---------------------------------------------------------------------------

def classify_token(token: str, html: str) -> str:
    """surfaced / ambiguous / unsurfaced for one op or tool name.

    A match is the token as a complete quoted string ('x', "x" or `x`).
    Generic names — no underscore — false-positive easily ('list', 'show',
    'set'), so a generic match lands in the ambiguous bin for human review
    instead of counting as surfaced."""
    quoted = re.compile(r"""['"`]""" + re.escape(token) + r"""['"`]""")
    if not quoted.search(html):
        return "unsurfaced"
    if "_" not in token:
        return "ambiguous"
    return "surfaced"


def classify_inventory(rows: list[dict], html: str) -> list[dict]:
    out = []
    for row in rows:
        out.append({**row, "state": classify_token(row["match_token"], html)})
    return out


# ---------------------------------------------------------------------------
# Module roll-up — static import closure from mcp_server
# ---------------------------------------------------------------------------

def _module_name(path: Path) -> str:
    rel = path.relative_to(PACKAGE_DIR)
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts) if parts else ""


def _static_imports(src: str, importer: str, is_init: bool = False) -> set[str]:
    """Package-relative names this source imports, resolved within the
    workspaces package (handles ``from .x import``, ``from .sub.x import``,
    ``from workspaces.x import`` and lazy in-function imports alike). A
    package __init__ is its own containing package, so its single-dot
    imports resolve inside the package rather than one level up."""
    found: set[str] = set()
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return found
    if not importer:
        pkg_parts = []
    elif is_init:
        pkg_parts = importer.split(".")
    else:
        pkg_parts = importer.split(".")[:-1]
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if node.level > 0:
                base = pkg_parts[: len(pkg_parts) - (node.level - 1)]
                mod = ".".join(base + (node.module.split(".") if node.module else []))
                if mod:
                    found.add(mod)
                for alias in node.names:
                    found.add((mod + "." if mod else "") + alias.name)
            elif node.module and node.module.split(".")[0] == "workspaces":
                mod = ".".join(node.module.split(".")[1:])
                if mod:
                    found.add(mod)
                for alias in node.names:
                    found.add((mod + "." if mod else "") + alias.name)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                parts = alias.name.split(".")
                if parts[0] == "workspaces" and len(parts) > 1:
                    found.add(".".join(parts[1:]))
    return found


def build_module_rollup() -> dict[str, str]:
    """module -> 'reached' | 'internal-declared' | 'cli-contract' | 'unreferenced'.

    Reached means in the transitive static-import closure of mcp_server.
    A docstring carrying "internal by design" exempts a module from the
    unreferenced bin (and from the CI gate). Cli-contract means the module is
    named in ``APPROVED_NONVISUAL_CONTRACTS``: a hand-authored, documented
    supported operation whose surface is the CLI or MCP rather than a console
    panel, so its absence from the console is not a surface gap. Reach and an
    internal declaration both outrank the registry — a registered module that
    is also reached or declared internal reports under the stronger class."""
    sources: dict[str, str] = {}
    # Finder/iCloud duplicate artifacts ("foo 2.py", "foo copy.py") are gitignored
    # but rglob walks the live filesystem, so a stray sync artifact would register
    # as a new unreferenced module — skip the same shapes .gitignore excludes.
    dup_artifact = re.compile(r" (\d{1,2}|copy( \d+)?)\.py$")
    for path in sorted(PACKAGE_DIR.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        if dup_artifact.search(path.name):
            continue
        name = _module_name(path)
        if not name or name.startswith("_"):
            continue
        sources[name] = (path.read_text(encoding="utf-8", errors="replace"),
                         path.name == "__init__.py")

    def resolve(name: str) -> str | None:
        # "sub.mod.symbol" resolves to the longest prefix that is a module
        parts = name.split(".")
        while parts:
            candidate = ".".join(parts)
            if candidate in sources:
                return candidate
            parts.pop()
        return None

    edges: dict[str, set[str]] = {}
    for name, (src, is_init) in sources.items():
        edges[name] = {m for m in map(resolve, _static_imports(src, name, is_init)) if m}

    def closure(roots: Iterable[str]) -> set[str]:
        seen: set[str] = set()
        frontier = list(roots)
        while frontier:
            current = frontier.pop()
            if current in seen or current not in sources:
                continue
            seen.add(current)
            frontier.extend(edges.get(current, ()))
        return seen

    reached = closure(["mcp_server"])

    rollup: dict[str, str] = {}
    for name, (src, _is_init) in sources.items():
        if name in reached:
            rollup[name] = "reached"
            continue
        doc = ast.get_docstring(ast.parse(src)) or ""
        if INTERNAL_MARK in doc.lower():
            rollup[name] = "internal-declared"
        elif name in APPROVED_NONVISUAL_CONTRACTS:
            rollup[name] = "cli-contract"
        else:
            rollup[name] = "unreferenced"
    return rollup


# ---------------------------------------------------------------------------
# Baseline gate
# ---------------------------------------------------------------------------

def gate_against_baseline(unsurfaced_ops: list[str], unreferenced_modules: list[str],
                          baseline: dict) -> tuple[list[str], list[str]]:
    """Returns (new_ops, new_modules) not present in the committed baseline."""
    known_ops = set(baseline.get("unsurfaced_ops", []))
    known_mods = set(baseline.get("unreferenced_modules", []))
    return (sorted(set(unsurfaced_ops) - known_ops),
            sorted(set(unreferenced_modules) - known_mods))


def main() -> int:
    html = load_composed_html()
    mcp = load_mcp_module()
    rows = classify_inventory(build_op_inventory(mcp), html)
    rollup = build_module_rollup()

    by_state = {"surfaced": [], "ambiguous": [], "unsurfaced": []}
    for row in rows:
        by_state[row["state"]].append(row)

    unsurfaced_ops = sorted(f"{r['facade']}.{r['op'] or ''}".rstrip(".") for r in by_state["unsurfaced"])
    unreferenced_modules = sorted(n for n, s in rollup.items() if s == "unreferenced")

    print("=" * 74)
    print("RVND SURFACE VERIFIER  ", time.strftime("%Y-%m-%d %H:%M:%S"))
    print("=" * 74)
    facades: dict[str, dict[str, int]] = {}
    for row in rows:
        c = facades.setdefault(row["facade"], {"surfaced": 0, "ambiguous": 0, "unsurfaced": 0})
        c[row["state"]] += 1
    for facade, c in sorted(facades.items()):
        total = sum(c.values())
        print(f"  {facade:26} {total:3} ops   {c['surfaced']:3} surfaced"
              f"  {c['ambiguous']:3} ambiguous  {c['unsurfaced']:3} unsurfaced")
    print("-" * 74)
    print(f"  ops: {len(rows)} total — {len(by_state['surfaced'])} surfaced,"
          f" {len(by_state['ambiguous'])} ambiguous, {len(by_state['unsurfaced'])} unsurfaced")
    mod_counts = {s: sum(1 for v in rollup.values() if v == s)
                  for s in ("reached", "internal-declared", "cli-contract",
                            "unreferenced")}
    print(f"  modules: {len(rollup)} total — {mod_counts['reached']} reached,"
          f" {mod_counts['internal-declared']} internal-declared,"
          f" {mod_counts['cli-contract']} cli-contract,"
          f" {mod_counts['unreferenced']} unreferenced")
    if mod_counts["cli-contract"]:
        print("  cli-contract modules (registered approved non-visual contracts):")
        for name in sorted(n for n, s in rollup.items() if s == "cli-contract"):
            print(f"    - {name}: {APPROVED_NONVISUAL_CONTRACTS.get(name, '')}")
    if by_state["unsurfaced"]:
        print("  unsurfaced ops:")
        for name in unsurfaced_ops:
            print(f"    - {name}")

    result = {
        "generated": time.strftime("%Y-%m-%d"),
        "ops": rows,
        "modules": rollup,
        "unsurfaced_ops": unsurfaced_ops,
        "unreferenced_modules": unreferenced_modules,
    }

    if "--json" in sys.argv:
        out = Path(sys.argv[sys.argv.index("--json") + 1])
        out.write_text(json.dumps(result, indent=1) + "\n", encoding="utf-8")
        print(f"  json -> {out}")

    if "--write-baseline" in sys.argv:
        BASELINE.write_text(json.dumps(
            {"unsurfaced_ops": unsurfaced_ops,
             "unreferenced_modules": unreferenced_modules}, indent=1) + "\n",
            encoding="utf-8")
        print(f"  baseline -> {BASELINE}")

    if "--ledger" in sys.argv:
        write_ledger(result)
        print(f"  ledger -> {LEDGER}")

    baseline = json.loads(BASELINE.read_text(encoding="utf-8")) if BASELINE.exists() else {}
    new_ops, new_mods = gate_against_baseline(unsurfaced_ops, unreferenced_modules, baseline)
    print("-" * 74)
    if not BASELINE.exists():
        print("RESULT: NO BASELINE — run with --write-baseline and commit it")
        return 1
    if new_ops or new_mods:
        for n in new_ops:
            print(f"  NEW unsurfaced op: {n}")
        for n in new_mods:
            print(f"  NEW unreferenced module: {n} (surface it, or declare"
                  f" \"{INTERNAL_MARK}\" in its docstring)")
        print("RESULT: SURFACE GAP GREW")
        return 1
    print("RESULT: NO NEW GAPS vs baseline")
    return 0


def write_ledger(result: dict) -> None:
    lines = [LEDGER_BEGIN, "",
             f"Snapshot {result['generated']}. The claim of record is"
             " `verify_surface.py`; regenerate with `python3 verify_surface.py --ledger`.", "",
             "| facade | op | state |", "|---|---|---|"]
    for row in result["ops"]:
        lines.append(f"| {row['facade']} | {row['op'] or '(tool)'} | {row['state']} |")
    lines += ["", "| module | reach |", "|---|---|"]
    for name, state in sorted(result["modules"].items()):
        if state != "reached":
            lines.append(f"| {name} | {state} |")
    lines += ["", LEDGER_END]
    generated = "\n".join(lines)

    if LEDGER.exists():
        text = LEDGER.read_text(encoding="utf-8")
        if LEDGER_BEGIN in text and LEDGER_END in text:
            head, rest = text.split(LEDGER_BEGIN, 1)
            _, tail = rest.split(LEDGER_END, 1)
            LEDGER.write_text(head + generated + tail, encoding="utf-8")
            return
    LEDGER.write_text(
        "# Surface ledger — console coverage of the engine\n\n" + generated + "\n",
        encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
