# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 flxk1
"""Concept test: build a requirements house from law NDs, place org docs in rooms."""

from __future__ import annotations

from rvnd.requirements_house import build_house_from_text
from rvnd.evidence_coverage import (
    EvidenceDoc, map_coverage, render_coverage,
)


AI_ACT = (
    "Providers of high-risk AI systems shall establish a risk management "
    "system. Providers of high-risk AI systems shall draw up the technical "
    "documentation before placing the system on the market. Deployers of "
    "high-risk AI systems shall keep the logs automatically generated by the "
    "system. Where the high-risk AI system is used for employment, the deployer "
    "shall carry out a data protection impact assessment under Regulation (EU) "
    "2016/679. Deployers shall designate a data protection officer."
)


def _house():
    return build_house_from_text(AI_ACT, "ai-act", title="EU AI Act — high-risk")


# --- house assembly ---------------------------------------------------------

def test_house_has_rooms_for_required_artifacts():
    h = _house()
    keys = {r.room_id for r in h.rooms}
    # the artifacts the text demands become rooms
    assert "dpia" in keys
    assert "risk-management-system" in keys
    assert "technical-documentation" in keys


def test_obligations_hang_in_their_artifact_room():
    h = _house()
    rms = h.room("risk-management-system")
    assert rms is not None
    # the "establish a risk management system" obligation hangs here
    assert any("risk management" in (o["action"] or "").lower()
               for o in rms.obligations)


def test_every_room_traces_to_a_source():
    h = _house()
    for r in h.rooms:
        # a room is justified by either an artifact trigger or an obligation source
        assert r.sources or r.obligations


# --- coverage mapping (the payoff) -----------------------------------------

def _docs():
    return [
        EvidenceDoc("d1", "Data Protection Impact Assessment - Hiring Tool",
                    "This DPIA assesses the processing of applicant data..."),
        EvidenceDoc("d2", "Enterprise Risk Management System Policy",
                    "Our risk management system identifies and mitigates risks..."),
        EvidenceDoc("d3", "Q3 Marketing Plan",
                    "Social media calendar and ad spend for the next quarter."),
    ]


def test_furnished_rooms_get_their_documents():
    h = _house()
    rep = map_coverage(h, _docs())
    furnished_ids = {f["room_id"] for f in rep.furnished}
    assert "dpia" in furnished_ids
    assert "risk-management-system" in furnished_ids
    # the DPIA doc landed in the dpia room
    dpia = next(f for f in rep.furnished if f["room_id"] == "dpia")
    assert any(d["doc_id"] == "d1" for d in dpia["documents"])


def test_empty_rooms_are_surfaced_as_gaps():
    h = _house()
    rep = map_coverage(h, _docs())
    empty_ids = {e["room_id"] for e in rep.empty}
    # nothing furnishes technical documentation / logs / DPO → gaps
    assert "technical-documentation" in empty_ids
    assert "logs" in empty_ids or "dpo" in empty_ids


def test_irrelevant_document_is_an_orphan():
    h = _house()
    rep = map_coverage(h, _docs())
    assert any(o["doc_id"] == "d3" for o in rep.orphans)


def test_coverage_ratio_is_between_0_and_1():
    h = _house()
    rep = map_coverage(h, _docs())
    assert 0.0 <= rep.coverage_ratio <= 1.0
    # 2 furnished of (2 + several empty) → < 1.0, > 0
    assert 0.0 < rep.coverage_ratio < 1.0


def test_low_relevance_doc_does_not_falsely_furnish():
    # a document that only vaguely mentions a room must NOT count as evidence
    h = _house()
    docs = [EvidenceDoc("x", "Random memo", "we talked about risk over lunch")]
    rep = map_coverage(h, docs)
    # 'risk' alone is below the placement floor for the risk-management room
    assert any(o["doc_id"] == "x" for o in rep.orphans)


def test_render_coverage_shows_all_three_sections():
    h = _house()
    rep = map_coverage(h, _docs())
    text = render_coverage(h, rep)
    assert "FURNISHED ROOMS" in text
    assert "EMPTY ROOMS — GAPS" in text
    assert "ORPHAN DOCUMENTS" in text
    assert "not legal advice" in text.lower()
