# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 flxk1
"""Regression fixtures from real EU statutory text (Layer-0 precision fixes).

These four provisions were fetched from official/authoritative sources and run
through the deterministic extractors (no LLM). They lock in the Layer-0
corrections:

  * AI Act Art. 26 must NOT mis-fire a ``trademark`` facet on "mark".
  * AI Act Art. 26 deployer bearer is "deployers of high-risk ai systems"
    (hyphen + acronym), not the truncated "risk ai systems".
  * AI Act Art. 5 "shall be prohibited" passive voice → operator F, not O/R.
  * Cross-references resolve the AI Act → GDPR link with CELEX.
  * Required-artifact scan finds the DPA / DPIA / TOMs the text presupposes.

The provisions are inlined (not network-fetched) so the test is hermetic.
"""

from __future__ import annotations

from rvnd.nd_routing import DefaultClassifier
from rvnd.adapters.deontic import OP_PROHIBITION, OP_PERMISSION
from rvnd.deontic_facets import extract_formulae
from rvnd.crossref_extractor import extract_cross_references
from rvnd.decisions.extractor import extract_decisions
from rvnd.instrument_obligation_extractor import extract_required_artifacts


GDPR_ART28 = (
    "Where processing is to be carried out on behalf of a controller, the "
    "controller shall use only processors providing sufficient guarantees to "
    "implement appropriate technical and organisational measures. The processor "
    "shall not engage another processor without prior specific or general "
    "written authorisation of the controller. Processing by a processor shall "
    "be governed by a contract or other legal act under Union or Member State "
    "law."
)

AIACT_ART5 = (
    "The following AI practices shall be prohibited: the placing on the market, "
    "the putting into service or the use of an AI system that deploys subliminal "
    "techniques beyond a person's consciousness. The use of an AI system that "
    "exploits any of the vulnerabilities of a natural person shall be prohibited. "
    "The provider shall not place such a system on the market. This Regulation "
    "applies without prejudice to Regulation (EU) 2016/679 and Directive "
    "2002/58/EC. Member States may decide to authorise the use of real-time "
    "remote biometric identification systems for the purposes of law enforcement."
)

AIACT_ART26 = (
    "Deployers of high-risk AI systems shall take appropriate technical and "
    "organisational measures to ensure they use such systems in accordance with "
    "the instructions for use. Where deployers carry out a data protection "
    "impact assessment under Regulation (EU) 2016/679, they shall use the "
    "information referred to in Article 13. Deployers shall keep the logs "
    "automatically generated by that high-risk AI system."
)

# The full Art. 5(1) opening sentence — long, with a relative clause that never
# reaches the passive modal until ~200 chars in. This is the input that hung the
# extractor when the passive-prohibition subject used a lazy ``(?:\s+WORD){0,8}?``
# group (catastrophic backtracking). Kept here as a ReDoS regression fixture.
AIACT_ART5_LONG = (
    "The following AI practices shall be prohibited: the placing on the market, "
    "the putting into service or the use of an AI system that deploys subliminal "
    "techniques beyond a person's consciousness or purposefully manipulative or "
    "deceptive techniques, with the objective or the effect of materially "
    "distorting the behaviour of a person or a group of persons by appreciably "
    "impairing their ability to make an informed decision, thereby causing them "
    "to take a decision that they would not have otherwise taken in a manner that "
    "causes or is reasonably likely to cause that person, another person or group "
    "of persons significant harm. The provider shall not place such a system on "
    "the market. The deployer must not use such a system. This Regulation applies "
    "without prejudice to Regulation (EU) 2016/679."
)


# --- ReDoS / performance guard ---------------------------------------------

def test_long_prohibition_sentence_does_not_hang():
    """The passive-prohibition pattern must be linear, not catastrophically
    backtracking, on a long sentence whose subject runs ~200 chars before the
    modal. Guards the bug where a lazy ``(?:\\s+WORD){0,8}?`` group froze the
    extractor on the real Art. 5(1) text. Must complete well under a second."""
    import time
    start = time.monotonic()
    formulae = extract_formulae(AIACT_ART5_LONG)
    elapsed = time.monotonic() - start
    assert elapsed < 2.0, f"extraction took {elapsed:.1f}s — possible ReDoS"
    # And it still finds the prohibition + the cross-reference downstream.
    assert OP_PROHIBITION in [f.operator for f in formulae]


# --- facet precision -------------------------------------------------------

def test_aiact_art26_does_not_misfire_trademark_facet():
    cls = DefaultClassifier().classify(AIACT_ART26)
    assert "ai-act" in cls.facets
    assert "trademark" not in cls.facets   # was a false positive on "mark"


def test_gdpr_art28_classified_normative_gdpr():
    cls = DefaultClassifier().classify(GDPR_ART28)
    assert cls.primary_type == "normative"
    assert "gdpr" in cls.facets


# --- deontic operator precision --------------------------------------------

def test_aiact_art5_passive_prohibition_is_F_not_O():
    formulae = extract_formulae(AIACT_ART5)
    ops = [f.operator for f in formulae]
    # The "shall be prohibited" sentence must be a prohibition.
    assert OP_PROHIBITION in ops
    # And the "may decide to authorise" Member-State sentence is a permission.
    assert OP_PERMISSION in ops


def test_aiact_art5_prohibition_bearer_is_clean_for_canonical_sentence():
    formulae = extract_formulae(AIACT_ART5)
    prohibitions = [f for f in formulae if f.operator == OP_PROHIBITION]
    assert any("following ai practices" in f.bearer for f in prohibitions)
    # The enumerated practice is captured as the action, not left empty.
    canonical = next(f for f in prohibitions if "following ai practices" in f.bearer)
    assert "placing on the market" in canonical.action


def test_aiact_art26_deployer_bearer_keeps_hyphen_and_acronym():
    formulae = extract_formulae(AIACT_ART26)
    bearers = [f.bearer for f in formulae]
    # Was truncated to "risk ai systems"; must now keep the full noun phrase.
    assert any("deployers of high-risk ai systems" in b for b in bearers)


# --- cross-document references ----------------------------------------------

def test_aiact_art5_links_to_gdpr_with_celex():
    refs = extract_cross_references(AIACT_ART5, host_key="ai-act")
    gdpr = next((r for r in refs if r.target_key == "gdpr"), None)
    assert gdpr is not None
    assert gdpr.target_celex == "32016R0679"
    assert gdpr.relation == "without-prejudice"


def test_aiact_art26_refers_to_gdpr():
    refs = extract_cross_references(AIACT_ART26, host_key="ai-act")
    assert any(r.target_key == "gdpr" for r in refs)


# --- decisions --------------------------------------------------------------

def test_aiact_art5_member_state_choice_is_a_decision():
    decisions = extract_decisions(AIACT_ART5)
    assert any(d.decider == "member states" for d in decisions)


# --- required artifacts -----------------------------------------------------

def test_gdpr_art28_requires_dpa_and_toms():
    arts = {a.key for a in extract_required_artifacts(GDPR_ART28)}
    assert "dpa" in arts
    assert "toms" in arts


def test_aiact_art26_requires_dpia_and_logs():
    arts = {a.key for a in extract_required_artifacts(AIACT_ART26)}
    assert "dpia" in arts
    assert "logs" in arts
